const plants = [
  {
    common_name: "spider plant",
    scientific_name: "chlorophytum comosum",
    climate: "temperate",
    watering: 2,
    sunlight: 3,
  },
  {
    common_name: "peace lily",
    scientific_name: "spathiphyllum wallisii",
    climate: "tropical",
    watering: 2,
    sunlight: 2,
  },
  {
    common_name: "snake plant",
    scientific_name: "sansevieria trifasciata",
    climate: "tropical",
    watering: 1,
    sunlight: 4,
  },
  {
    common_name: "aloe vera",
    scientific_name: "aloe barbadensis miller",
    climate: "subtropical",
    watering: 1,
    sunlight: 5,
  },
  {
    common_name: "rubber plant",
    scientific_name: "ficus elastica",
    climate: "tropical",
    watering: 2,
    sunlight: 3,
  },
  {
    common_name: "zz plant",
    scientific_name: "zamioculcas zamiifolia",
    climate: "tropical",
    watering: 1,
    sunlight: 3,
  },
  {
    common_name: "fiddle leaf fig",
    scientific_name: "ficus lyrata",
    climate: "tropical",
    watering: 3,
    sunlight: 4,
  },
  {
    common_name: "boston fern",
    scientific_name: "nephrolepis exaltata",
    climate: "tropical",
    watering: 3,
    sunlight: 2,
  },
  {
    common_name: "philodendron",
    scientific_name: "philodendron bipinnatifidum",
    climate: "tropical",
    watering: 2,
    sunlight: 3,
  },
  {
    common_name: "jade plant",
    scientific_name: "crassula ovata",
    climate: "subtropical",
    watering: 1,
    sunlight: 5,
  },
  {
    common_name: "pothos",
    scientific_name: "epipremnum aureum",
    climate: "tropical",
    watering: 2,
    sunlight: 3,
  },
  {
    common_name: "chinese evergreen",
    scientific_name: "aglaonema modestum",
    climate: "tropical",
    watering: 2,
    sunlight: 2,
  },
  {
    common_name: "dracaena",
    scientific_name: "dracaena marginata",
    climate: "tropical",
    watering: 2,
    sunlight: 4,
  },
  {
    common_name: "english ivy",
    scientific_name: "hedera helix",
    climate: "temperate",
    watering: 2,
    sunlight: 3,
  },
  {
    common_name: "asparagus fern",
    scientific_name: "asparagus setaceus",
    climate: "tropical",
    watering: 2,
    sunlight: 3,
  },
  {
    common_name: "calathea",
    scientific_name: "calathea orbifolia",
    climate: "tropical",
    watering: 3,
    sunlight: 2,
  },
  {
    common_name: "monstera",
    scientific_name: "monstera deliciosa",
    climate: "tropical",
    watering: 2,
    sunlight: 3,
  },
  {
    common_name: "prayer plant",
    scientific_name: "maranta leuconeura",
    climate: "tropical",
    watering: 3,
    sunlight: 2,
  },
  {
    common_name: "succulent",
    scientific_name: "echeveria spp.",
    climate: "subtropical",
    watering: 1,
    sunlight: 5,
  },
  {
    common_name: "cactus",
    scientific_name: "cactaceae spp.",
    climate: "desert",
    watering: 1,
    sunlight: 5,
  },
];

module.exports = plants;
